# frozen_string_literal: true

source "https://rubygems.org"

gemspec path: "../bundler", development_group: :test
gemspec path: "../cargo", development_group: :test
gemspec path: "../common", development_group: :test
gemspec path: "../composer", development_group: :test
gemspec path: "../docker", development_group: :test
gemspec path: "../elm", development_group: :test
gemspec path: "../github_actions", development_group: :test
gemspec path: "../git_submodules", development_group: :test
gemspec path: "../go_modules", development_group: :test
gemspec path: "../gradle", development_group: :test
gemspec path: "../hex", development_group: :test
gemspec path: "../maven", development_group: :test
gemspec path: "../npm_and_yarn", development_group: :test
gemspec path: "../nuget", development_group: :test
gemspec path: "../pub", development_group: :test
gemspec path: "../python", development_group: :test
gemspec path: "../terraform", development_group: :test

gem "activesupport", "~> 6.1.4"
gem "http", "~> 5.1"
gem "octokit", "4.25.1"
gem "sentry-raven", "~> 3.1"
gem "terminal-table", "~> 3.0.2"

group :development do
  gem "licensed", "~> 3.8", require: false
end
